/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.madlabs.patternrec.web.rest.api;

import io.swagger.annotations.*;
import it.madlabs.patternrec.web.rest.controllers.common.ServerErrorException;
import it.madlabs.patternrec.web.rest.model.ErrorModel;
import it.madlabs.patternrec.web.rest.model.Point;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-30T20:32:37.777Z")

@Api(value = "", description = "the point API")
public interface SpaceApi {

    @ApiOperation(value = "/space", notes = "Get all points in the space  GET /space  Example response [   {\"x\": 2, \"y\": 3},   {\"x\": -2, \"y\": 1023},   {\"x\": 3.2, \"y\": 0}, ... ] ", response = Point.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "all points present in the space", response = Point.class, responseContainer = "List"),
        @ApiResponse(code = 500, message = "Unexpected Error", response = ErrorModel.class) })
    
    @RequestMapping(value = "/space",
        produces = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Point>> allPoints() throws ServerErrorException;


    @ApiOperation(value = "/space", notes = "Remove all points from the space DELETE /space ", response = Void.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "all points deleted", response = Void.class),
        @ApiResponse(code = 500, message = "Unexpected Error", response = ErrorModel.class) })
    
    @RequestMapping(value = "/space",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteAllPoints();

}
